---
name: Paul
surname: Sabourenkov

position: "Computational Biologist"

profilepic: "Paul.jpg"

address: "Taringa, QLD 4068, Australia"
phone: +61 421 583 518
email: "paul.sabourenkov@uq.net.au"
github: "gimme00"
# www: "www.linkedin.com/in/psabourenkov"
linkedin: psabourenkov

aboutme: MBioinf(Adv), BSc(Hons)Psych, BSc(Hons)CompSci, Assoc.MAPS
  
headcolor: 333399
#docname: 'CV'

date: "`r format(Sys.time(), '%B %Y')`"

# fontawesome: yes
output: 
  vitae::awesomecv:
    keep_tex: false
always_allow_html: no

papersize: a4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(kableExtra)
library(tibble)
library(fontawesome)
library(rsvg)
options(knitr.table.format = "html")
# fa_html_dependency()
p <- function(text) { text_spec(text, background = "#333399", color = "white", bold = T, font_size = 6) }
cat_tags <- function(tags) { paste(sapply(tags, p), sep = '', collapse = ' ') }
```

# Education

```{r education}
degrees <- tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ Details,
  "M.Bioinformatics (Advanced)", 2015, "University of Queensland", "St Lucia, Queensland",
      c("research into cancer genomics using interaction network analysis to identify novel drug targets in medulloblastoma",
        "supervised by Dr. Melissa Davis",
        "at Prof. Brandon Wainwright group at the Institute for Molecular Bioscience, UQ"),
  "B.Sc. (Honours) Psychology", 2009, "University of Tasmania", "Hobart, Tasmania",
      c("research into effect of cognitive processes on cortical plasticity with respect to human motor control and post-stroke rehabilitation",
        "human neuroscience focus",
        "advanced topics in bioethics, theoretical controversies, clinical psychology, research methods and statistics"),
  "Grad. Dip. Sc. Psychology", 2008, "University of Tasmania and Monash", "Hobart, Tasmania",
      c("Australian Psychological Society accredited","focus on clinical, social, and developmental psychology, and psychological testing as well as neuroscience","three year core in statistics and research methods"),
  "B.Sc. (Honours) Computer Science", 1997, "University of Tasmania", "Hobart, Tasmania",
    c("research into optimality in artificial neural networks",
      "advanced topics in operating systems and networks, simulation, discrete and continuous modelling, concurrency and supercomputing, artificial intelligence, expert systems, computer languages, functional programming, and advanced VLSI design"),
  "B.Sc. Computer Science", 1995, "University of Tasmania", "Hobart, Tasmania",
      c("principles of computer science and software engineering, computer languages, metaprogramming, functional programming, systems analysis, databases, computer architecture and VLSI design, networking, artificial intelligence, computer graphics, and digital image processing","mathematics including discrete mathematics, linear algebra, operations research and optimisation, multivariate calculus, abstract algebra, computational methods, and cryptography")
)

degrees %>% detailed_entries(Degree, Year, Institution, Where, Details)
```


# Publications

```{r publications}
bib <- bibliography_entries(here::here("bibliography.bib"))

bib %>% dplyr::arrange(desc(as.Date(issued)))
```

# Short Courses

```{r short_courses}
tribble(
  ~Year, ~Course, ~Where,
  2012, "Drugs and the Brain (Neuropharmacology)", "California Institute of Technology",
  2012, "Fundamentals of Pharmacology", "University of Pennsylvania",
  2001, "Certificate of English Language Teaching to Adults (CELTA)", "Cambridge College of English (CIC)"
) %>% 
  brief_entries(
    Course,
    Year, 
    Where
  )
```

# Recognition and Professional Memberships

```{r recognition}
tribble(
  ~Year, ~Where, ~What,
  2014, "Australian Bioinformatics and Computational Biology Society (ABACBS)", "Member",
  2010, "Golden Key International Honour Society", "Member",
  2010, "Australian Psychological Society", "Assoc. MAPS",
  1996, "Australian Computer Society", "MACS"
) %>% 
  brief_entries(
    Where,
    Year, 
    What
  )
```

# Career Profile

```{r career_profile}
tribble(
  ~Year, ~Title, ~Where,
  "2016-2021", "Computational Biologist (Pharmacometrics)", "DoseMe Pty.Ltd.",
  "2015-2017", "Consultant (Databases)", "CMLR, UQ",
  "2014-2015", "Bioinformatician (Cancer Genomics)", "IMB, UQ",
  "2010-2013", "Software Engineer (Machine Control)", "Leica Geosystems",
  "2007-2010", "Senior Systems Analys (Systems)", "Tote Tasmania",
  "2004-2007", "Senior Developer (Databases)", "Tote Tasmania",
  "2001-2004", "Software Development Team Leader (Systems)", "Tote Tasmania",
  "1999-2000", "GIS Data Analyst, Statistician", "CSIRO Division of Marine Research",
  "1999-2000", "Software Developer (Scientific Software)", "CSIRO Division of Marine Research",
  "1998-1998", "Software Developer (Simulation and Modelling)", "University of Tasmania",
  "1991-1992", "Software Developer (Finance)", "Open Look Software",
  "1989-1989", "Support Programmer (Process Control)", "Skobeltsyn Institute of Nuclear Physics"
) %>% 
  brief_entries(
    what = Title,
    when = Year, 
    with = Where
  )
```

# Select Skills

```{r tags}
tags <- yaml::read_yaml(here::here("data-raw/tags.yaml"))
```

`r cat_tags( tags$areas )`

`r cat_tags( tags$technologies )`

`r cat_tags( tags$social_coding )`

`r cat_tags( tags$languages )`

# One More Thing

## This CV is written in R and Markdown, you can view the source code on github
## [https://github.com/frctlcdr/paulsab-cv](https://github.com/frctlcdr/paulsab-cv)

